### Clip

In [3]:
from diffuser_actor.utils.clip import load_clip
model=load_clip()

In [6]:
model

(ModifiedResNetFeatures(
   (conv1): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
   (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
   (relu1): ReLU(inplace=True)
   (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
   (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
   (relu2): ReLU(inplace=True)
   (conv3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
   (bn3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
   (relu3): ReLU(inplace=True)
   (avgpool): AvgPool2d(kernel_size=2, stride=2, padding=0)
   (layer1): Sequential(
     (0): Bottleneck(
       (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
       (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
       (relu1): ReLU(inplace=True)
       (conv2): Conv2d(64, 64

In [9]:
import clip
clip_model,clip_transforms=clip.load("RN50")
state_dict=clip_model.state_dict()

In [17]:
state_dict["visual.layer1.0.conv1.weight"].shape

torch.Size([64, 64, 1, 1])

In [95]:
import torch.nn as nn

# Example model
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(10, 5)
        self.fc2 = nn.Linear(5, 2)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        return x

model = SimpleModel()

# Iterate over named parameters
for name, param in model.named_parameters():
    print(f"Parameter name: {name}")
    print(f"Parameter value: {param}")

Parameter name: fc1.weight
Parameter value: Parameter containing:
tensor([[ 0.2732,  0.1868,  0.2293,  0.1355,  0.2190, -0.1565,  0.2926, -0.0988,
         -0.2663, -0.1043],
        [-0.1215,  0.2113,  0.0214, -0.2280,  0.3085,  0.1476, -0.0819,  0.0635,
         -0.2802, -0.1480],
        [ 0.0903,  0.0054,  0.2649,  0.1893, -0.0781,  0.2863, -0.2610, -0.0616,
         -0.2822,  0.2090],
        [ 0.2380, -0.2238, -0.0912,  0.0583,  0.1545, -0.1454, -0.1203, -0.1594,
          0.0965,  0.0018],
        [ 0.2664, -0.3153, -0.2292, -0.2796,  0.1024, -0.0325,  0.3076,  0.2635,
          0.0398,  0.2119]], requires_grad=True)
Parameter name: fc1.bias
Parameter value: Parameter containing:
tensor([ 0.3049, -0.2522,  0.1003,  0.2775,  0.0900], requires_grad=True)
Parameter name: fc2.weight
Parameter value: Parameter containing:
tensor([[-0.1111,  0.1486, -0.4279, -0.3992, -0.1350],
        [ 0.0601,  0.0858,  0.0456,  0.0592,  0.4144]], requires_grad=True)
Parameter name: fc2.bias
Paramete

### Data loading

In [5]:
import os
import pickle
print(os.getcwd())

/home/yujun.lin/Documents/diffusion_policy/3d_diffuser_actor


In [4]:
instruction_file='./instructions/peract/instructions.pkl'

In [12]:

with open(instruction_file, 'rb') as f:
    instructions = pickle.load(f)
for k,v in instructions.items():
    print(k)
print('number of keys:', len(instructions.keys()))

open_fridge
stack_wine
open_drawer
toilet_seat_down
put_money_in_safe
put_books_on_bookshelf
open_box
meat_off_grill
take_usb_out_of_computer
lamp_on
place_shape_in_shape_sorter
wipe_desk
close_laptop_lid
close_grill
play_jenga
unplug_charger
put_groceries_in_cupboard
push_button
stack_cups
take_money_out_safe
sweep_to_dustpan_of_size
take_lid_off_saucepan
take_umbrella_out_of_umbrella_stand
straighten_rope
open_grill
beat_the_buzz
lamp_off
plug_charger_in_power_supply
light_bulb_in
close_door
meat_on_grill
stack_blocks
slide_block_to_color_target
put_item_in_drawer
put_rubbish_in_bin
open_window
take_frame_off_hanger
scoop_with_spatula
put_umbrella_in_umbrella_stand
press_switch
open_door
open_wine_bottle
close_fridge
reach_target
slide_cabinet_open_and_place_cups
toilet_seat_up
place_wine_at_rack_location
tower3
phone_on_base
change_channel
sweep_to_dustpan
pick_up_cup
close_microwave
lift_numbered_block
take_toilet_roll_off_stand
open_microwave
hang_frame_on_hanger
close_jar
turn_ta

In [17]:
instructions['place_cups'][0]

tensor([[[ 0.3393,  0.1165,  0.1019,  ...,  0.2468,  0.5906,  0.1013],
         [ 1.2096, -1.0002, -0.6230,  ..., -0.1125,  0.4838, -0.2585],
         [-0.1781, -1.2124,  0.0034,  ..., -0.7090,  0.8434,  0.2343],
         ...,
         [ 2.1463, -0.8304, -1.0359,  ...,  0.2642,  0.9770, -0.4717],
         [ 2.1739, -0.8271, -1.0595,  ...,  0.2685,  0.9662, -0.4592],
         [ 2.1981, -0.8129, -1.0651,  ...,  0.2809,  0.9446, -0.4516]],

        [[ 0.3393,  0.1165,  0.1019,  ...,  0.2468,  0.5906,  0.1013],
         [ 2.3039, -1.5309, -0.2537,  ...,  0.0676,  0.0238,  0.3786],
         [ 1.3264,  0.9941,  0.5533,  ...,  0.8062,  0.4343, -0.0677],
         ...,
         [ 1.7518, -1.4824, -2.0099,  ..., -0.7241,  0.2800, -1.7268],
         [ 1.7789, -1.4776, -2.0152,  ..., -0.7306,  0.2781, -1.7122],
         [ 1.8063, -1.4679, -2.0146,  ..., -0.7335,  0.2701, -1.7091]],

        [[ 0.3393,  0.1165,  0.1019,  ...,  0.2468,  0.5906,  0.1013],
         [ 1.3012, -0.6347, -0.7638,  ...,  0

In [20]:
a='hello! how are you?'
b=a.replace('~','!')
b

'hello! how are you?'

In [22]:
word='close_door'
class_name = "".join([w[0].upper() + w[1:] for w in word.split("_")])

class_name

'CloseDoor'